CREATE TABLE "GCG_4407_PRESS_COUNT"(
 "REC_ID" INTEGER DEFAULT '0' NOT NULL ,
 "JOB" CHAR(6),
 "SUFFIX" CHAR(3),
 "SEQ" CHAR(6),
 "WORKCENTER" CHAR(4),
 "EMPLOYEE" CHAR(5),
 "START_DATE" DATE,
 "START_COUNT" INTEGER,
 "STOP_COUNT" INTEGER,
 PRIMARY KEY ("REC_ID"),
 UNIQUE ("REC_ID"));